sudo: false


language: node_js
node_js:
  - stable

env:
  - BROWSER=ChromeCi
  - BROWSER=Firefox

cache:
  directories:
    - node_modules

after_script:
    - npm run coveralls

services:
  - xvfb

branches:
  only:
    - master
    - next
