name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:alpine
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
