name: Node.js CI

on:
  push:
    branches:
      - master
      - ci/github-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:alpine
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
