name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-version: [16, 17, 18]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm ci --force
      - run: npm run build
      - run: npm test -- --coverage
        env:
          REACT: ${{ matrix.react-version }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: React-${{ matrix.react-version }}
